<a href="https://colab.research.google.com/github/coderzaman/Neural-Networks-and-Fuzzy-Systems/blob/main/NNFS(LR_02)%5BImplement_forward_and_backward_pass_with_derivatives%5D_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. SETUP

In [49]:
import tensorflow as tf

# Input vector and true target value
x = tf.Variable([[0.8], [0.4], [0.3]], dtype=tf.float32)
y_true = tf.constant([[1.0]], dtype=tf.float32)

# Learning Rate
lr = 0.1

# Layer 1 weights and biases
W1 = tf.Variable([
    [0.20, -0.10, 0.30],
    [0.05, 0.40, -0.20],
    [0.10, 0.00, 0.25]
], dtype=tf.float32)
b1 = tf.Variable([[0.01], [0.02], [-0.03]], dtype=tf.float32)

# Layer 2 weights and biases
W2 = tf.Variable([
    [0.30, -0.20, 0.10],
    [0.60, 0.10, -0.40],
    [-0.50, 0.20, 0.20]
], dtype=tf.float32)
b2 = tf.Variable([[0.00], [0.05], [0.01]], dtype=tf.float32)

# Layer 3 weights and biases
W3 = tf.Variable([
    [0.20, 0.20, -0.10],
    [-0.30, 0.50, 0.30],
    [0.40, -0.20, 0.10]
], dtype=tf.float32)
b3 = tf.Variable([[0.02], [-0.01], [0.00]], dtype=tf.float32)

# Output Layer weights and biases
W4 = tf.Variable([[0.70], [-0.60], [0.50]], dtype=tf.float32)
b4 = tf.Variable([[0.10]], dtype=tf.float32) # Reshape b4 to match delta4

# 2. ACTIVATION FUNCTIONS & DERIVATIVES

In [50]:
def relu(x):
    return tf.maximum(0.0, x)

def relu_derivative(x):
    return tf.cast(x > 0, dtype=tf.float32)

def sigmoid(x):
    return 1 / (1 + tf.exp(-x))

def sigmoid_derivative(x):
    s = sigmoid(x)
    return s * (1 - s)

# 3. FORWARD PASS

In [51]:
# Layer 1
z1 = tf.matmul(W1, x) + b1
a1 = relu(z1)

# Layer 2
z2 = tf.matmul(W2, a1) + b2
a2 = relu(z2)

# Layer 3
z3 = tf.matmul(W3, a2) + b3
a3 = relu(z3)

# Layer 4 (Output)
z4 = tf.matmul(tf.transpose(W4), a3) + b4
y_hat = sigmoid(z4)

# 4. OUTPUT OF FORWARD PASS

In [52]:
 #--- Print Results ---
print("--- Feedforward Pass Results ---")
print(f"z1 =\n{z1.numpy()}\n")
print(f"a1 =\n{a1.numpy()}\n")
print(f"z2 =\n{z2.numpy()}\n")
print(f"a2 =\n{a2.numpy()}\n")
print(f"z3 =\n{z3.numpy()}\n")
print(f"a3 =\n{a3.numpy()}\n")
print(f"z4 =\n{z4.numpy()}\n")
print(f"y_hat (Final Output) =\n{y_hat.numpy()}\n")

--- Feedforward Pass Results ---
z1 =
[[0.22000001]
 [0.16000001]
 [0.125     ]]

a1 =
[[0.22000001]
 [0.16000001]
 [0.125     ]]

z2 =
[[ 0.0465    ]
 [ 0.14800002]
 [-0.04300001]]

a2 =
[[0.0465    ]
 [0.14800002]
 [0.        ]]

z3 =
[[ 0.0589    ]
 [ 0.05005001]
 [-0.011     ]]

a3 =
[[0.0589    ]
 [0.05005001]
 [0.        ]]

z4 =
[[0.1112]]

y_hat (Final Output) =
[[0.5277714]]



# 5. COMPUTE LOSS

In [53]:
loss = tf.square(y_true - y_hat)
print(f"--- Initial State ---")
print(f"Prediction (y_hat): {y_hat.numpy()[0][0]:.6f}")
print(f"Loss: {loss.numpy()[0][0]:.6f}\n")

--- Initial State ---
Prediction (y_hat): 0.527771
Loss: 0.223000



# 6. BACKPROPAGATION (ONE ITERATION)

In [54]:
# Layer 4 (Output Layer)
delta4 = 2*(y_hat - y_true) * sigmoid_derivative(z4)
dW4 = tf.matmul(a3, delta4)
db4 = delta4

# Layer 3
error3 = tf.matmul(W4, delta4)
delta3 = error3 * relu_derivative(z3)
dW3 = tf.matmul(delta3, a2, transpose_b=True)
db3 = delta3

# Layer 2
error2 = tf.matmul(W3, delta3, transpose_a=True)
delta2 = error2 * relu_derivative(z2)
dW2 = tf.matmul(delta2, a1, transpose_b=True)
db2 = delta2

# Layer 1
error1 = tf.matmul(W2, delta2, transpose_a=True)
delta1 = error1 * relu_derivative(z1)
dW1 = tf.matmul(delta1, x, transpose_b=True)
db1 = delta1

### UPDATE WIGHT AND BAYES

In [55]:
W1.assign_sub(lr * dW1)
b1.assign_sub(lr * db1)
W2.assign_sub(lr * dW2)
b2.assign_sub(lr * db2)
W3.assign_sub(lr * dW3)
b3.assign_sub(lr * db3)
W4.assign_sub(lr * dW4)
b4.assign_sub(lr * db4)

<tf.Variable 'UnreadVariable' shape=(1, 1) dtype=float32, numpy=array([[0.12353859]], dtype=float32)>

# 7. PRINT UPDATED WEIGHTS AND BIASES

In [56]:
print("--- Updated Weights and Biases after one iteration ---")
print("Updated W1:\n", W1.numpy())
print("\nUpdated b1:\n", b1.numpy())
print("\nUpdated W2:\n", W2.numpy())
print("\nUpdated b2:\n", b2.numpy())
print("\nUpdated W3:\n", W3.numpy())
print("\nUpdated b3:\n", b3.numpy())
print("\nUpdated W4:\n", W4.numpy())
print("\nUpdated b4:\n", b4.numpy())

--- Updated Weights and Biases after one iteration ---
Updated W1:
 [[ 0.2        -0.1         0.3       ]
 [ 0.04849353  0.39924678 -0.20056494]
 [ 0.10180777  0.00090388  0.2506779 ]]

Updated b1:
 [[ 0.01      ]
 [ 0.01811691]
 [-0.02774029]]

Updated W2:
 [[ 0.30165714 -0.19879483  0.10094155]
 [ 0.59917146  0.09939741 -0.40047076]
 [-0.5         0.2         0.2       ]]

Updated b2:
 [[0.00753235]
 [0.04623383]
 [0.01      ]]

Updated W3:
 [[ 0.20076619  0.20243861 -0.1       ]
 [-0.30065674  0.49790978  0.3       ]
 [ 0.4        -0.2         0.1       ]]

Updated b3:
 [[ 0.03647701]
 [-0.02412315]
 [ 0.        ]]

Updated W4:
 [[ 0.7013864 ]
 [-0.59882194]
 [ 0.5       ]]

Updated b4:
 [[0.12353859]]


#  8. MULTIPLE ITERATIONS (TRAINING LOOP)

In [57]:
epochs = 3000

for epoch in range(epochs):
    # --- Forward Pass ---
    z1 = tf.matmul(W1, x) + b1
    a1 = relu(z1)
    z2 = tf.matmul(W2, a1) + b2
    a2 = relu(z2)
    z3 = tf.matmul(W3, a2) + b3
    a3 = relu(z3)
    z4 = tf.matmul(tf.transpose(W4), a3) + b4
    y_hat = sigmoid(z4)

    # --- Compute Loss ---
    loss = tf.square(y_true - y_hat)

    # --- Stop if loss is zero ---
    if loss.numpy()[0][0] == 0:
        print(f"Loss reached zero at epoch {epoch+1}. Stopping training.")
        break

    # --- Backpropagation ---
    # Layer 4 (Output Layer)
    delta4 = 2 * (y_hat - y_true) * sigmoid_derivative(z4)
    dW4 = tf.matmul(a3, delta4)
    db4 = delta4

    # Layer 3
    error3 = tf.matmul(W4, delta4)
    delta3 = error3 * relu_derivative(z3)
    dW3 = tf.matmul(delta3, a2, transpose_b=True)
    db3 = delta3

    # Layer 2
    error2 = tf.matmul(W3, delta3, transpose_a=True)
    delta2 = error2 * relu_derivative(z2)
    dW2 = tf.matmul(delta2, a1, transpose_b=True)
    db2 = delta2

    # Layer 1
    error1 = tf.matmul(W2, delta2, transpose_a=True)
    delta1 = error1 * relu_derivative(z1)
    dW1 = tf.matmul(delta1, x, transpose_b=True)
    db1 = delta1

    # --- Parameter Update ---
    W1.assign_sub(lr * dW1)
    b1.assign_sub(lr * db1)
    W2.assign_sub(lr * dW2)
    b2.assign_sub(lr * db2)
    W3.assign_sub(lr * dW3)
    b3.assign_sub(lr * db3)
    W4.assign_sub(lr * dW4)
    b4.assign_sub(lr * db4)

    # --- Print progress after each 500 Iteration ---
    if (epoch + 1) % 500 == 0:
      print(f"Epoch {epoch+1}, Loss: {loss.numpy()[0][0]:.6f}")

Epoch 500, Loss: 0.000651
Epoch 1000, Loss: 0.000234
Epoch 1500, Loss: 0.000132
Epoch 2000, Loss: 0.000089
Epoch 2500, Loss: 0.000066
Epoch 3000, Loss: 0.000052


# 9. FINAL RESULTS AFTER TRAINING

In [58]:
print("\n--- Final Results After Training ---")
print(f"Final Prediction (y_hat): {y_hat.numpy()[0][0]:.6f}")
print(f"Final Loss: {loss.numpy()[0][0]:.6f}")


--- Final Results After Training ---
Final Prediction (y_hat): 0.992803
Final Loss: 0.000052
