<a href="https://colab.research.google.com/github/coderzaman/Neural-Networks-and-Fuzzy-Systems/blob/main/NNFS_Lab_05(CNN_Feature_Detector_and_map).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np
image = np.random.randint(0, 2, size=(7, 7))
feature_detector = np.random.randint(0, 2, size=(3, 3))
row = image.shape[0]-feature_detector.shape[0] + 1
col = image.shape[1]-feature_detector.shape[1] + 1
feature_map = np.zeros((row, col))

# print(image)
# print(feature_detector)

k_rows, k_cols = feature_detector.shape

for i in range(row):
    for j in range(col):

        image_window = image[i : i + k_rows, j : j + k_cols]

        multiplied_values = image_window * feature_detector

        output_value = np.sum(multiplied_values)

        feature_map[i, j] = output_value

print("\nCalculated Feature Map (5x5):")
print(feature_map)


[[1 0 0 1 1 0 0]
 [1 0 1 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 1 1 0 1 0 0]
 [1 1 1 0 1 0 1]
 [0 1 1 0 1 0 1]
 [1 0 1 1 0 1 1]]
[[1 1 0]
 [0 0 1]
 [1 0 0]]

Calculated Feature Map (5x5):
[[2. 0. 2. 2. 1.]
 [1. 2. 2. 2. 2.]
 [2. 1. 2. 0. 2.]
 [2. 3. 3. 1. 3.]
 [4. 2. 3. 2. 2.]]
